### ISSUE TITLE
Blurry Ship Sprites

### ISSUE THREAD

**Issue by BundtCake** [Dibujaron/DistantHorizonIssues#38]
Ship sprites appear blurry when compared to planets

**Comment by BundtCake** [comment]
![Screenshot_219](https://user-images.githubusercontent.com/39447293/103381549-f9bbf680-4aa0-11eb-9540-0d79309b7fdb.png)

**Comment by Dibujaron** [comment]
I attempted various strategies to fix this today and wasn't happy with any of the results - with freely-rotating pixel art like this, you get a lot of trouble with antialiasing. It looks really bad to deblur them. So going to close as won't do for now.
