### ISSUE TITLE
Velocity indication improvements

### ISSUE THREAD

**Issue by Dibujaron** [Dibujaron/DistantHorizonIssues#5]
"I wonder if a velocity indicator would be someone good to add to the game. Something that indicates direction and speed to help people stop going in the wrong direction"

One option would be breadcrumbs in front of you indicating where you're likely to go if no inputs are provided.

How to do this without cluttering the screen?

**Comment by Cweb118** [comment]
I am partial to the dot method that I think was mentioned a bit ago. Essentially you get maybe 10 dots showing your trajectory which then gives you a heading. As you speed up these dots will space out. If you are going super slow they will contract.
This could be done by having each dot represent where you will be in a quantity of time. So maybe each dot is a half second projection. This should avoid the velocity reference frame issue
